"""init

Revision ID: 321b02daec61
Revises: 794984518147
Create Date: 2019-08-30 18:23:49.039836

"""

# revision identifiers, used by Alembic.
revision = '321b02daec61'
down_revision = '794984518147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
