CHOOSING, TYPING_REPLY, TYPING_CHOICE, COUNTERS_CHOICE, ELECTRICITY_STATE, WATER_STATE, GAS_STATE, GAS_COUNTER_PHOTO_STATE, \
CALENDAR_STATE, EDIT_COUNTERS_DATA, UPDATE_RATES = range(11)
ELECTRICITY = 'electricity'
WATER = 'water'
GAS = 'gas'
GAS_COUNTER_PHOTO = 'gas_counter_photo_url'
EDIT_ENERGY = 'edit_energy'
EDIT_WATER = 'edit_water'
EDIT_GAS = 'edit_gas'
EDIT_COUNTERS_FIELDS = {
    EDIT_ENERGY: ELECTRICITY,
    EDIT_WATER: WATER,
    EDIT_GAS: GAS
}
