CHOOSING, TYPING_REPLY, TYPING_CHOICE, COUNTERS_CHOICE, ELECTRICITY_STATE, WATER_STATE, GAS_STATE, GAS_COUNTER_PHOTO, \
    CALENDAR_STATE = range(9)
ELECTRICITY = 'electricity'
WATER = 'water'
GAS = 'gas'
